#!/usr/bin/env sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then 
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
   xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

unclutter &		# Remove mouse when idle

exec dwmblocks 2>&1 >/dev/null &
exec xss-lock -- slock &
exec dunst &
exec clipmenud &
exec flameshot &


xcape -t 1000 -e 'Mode_switch=Escape'
while true; do
    # Log stderror to a file 
    # xmonad
    dwm 2> ~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
